name: json_to_dart
description: The tool to convert json to dart code.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=2.8.0"
dependencies:

  # collection: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dart_style: ^2.0.0
  dartx: any
  diff_match_patch: ^0.4.1  
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   
  flutter_smart_dialog: any     
  flutter_spinkit: ^5.1.0   
  get: any
  hive: any
  hive_flutter: any  
  intl: any
  nested: any


dependency_overrides:
  #dart_style: ^2.0.0
dev_dependencies:
  build_runner: any
  flutter_native_splash: ^1.1.7+1  
  flutter_test:
    sdk: flutter
  #hive_generator: any  
  hive_generator: 
    git:
      url: https://github.com/zmtzawqlp/hive.git
      path: hive_generator
  # hive_generator: 
  #   git:
  #     url: https://gitee.com/zmtzawqlp/hive.git
  #     path: hive_generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
    
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto/Roboto-Thin.ttf
  #         weight: 100
  #       - asset: fonts/Roboto/Roboto-Light.ttf
  #         weight: 300
  #       - asset: fonts/Roboto/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: fonts/Roboto/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Roboto/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Roboto/Roboto-Black.ttf
  #         weight: 900
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#42a5f5"
  image: web/favicon.png